### ISSUE TITLE
Wallet Private Key should be hidden by default

### ISSUE THREAD

**Issue by barbaraliau** [paychant/celo-web-wallet#1]
This is a great project and the UI is great!

I'd like to suggest that the Wallet Private Key be hidden by default. Since this is a private key, the UI should convey that by hiding it on load and requiring the user to toggle between hide/show. It would also help to have some sort of tooltip or prompt warning users that this is their private key and they shouldn't send it to anyone.

**Comment by paychant** [comment]
<img width="705" alt="this" src="https://user-images.githubusercontent.com/72511177/99798424-4c64d300-2b31-11eb-8557-06431ef5f0a5.png">

Thanks @barbaraliau, We've added a toggle button to show/hide users private key.

Thanks.
