### ISSUE TITLE
Update cGLD to CELO

### ISSUE THREAD

**Issue by barbaraliau** [paychant/celo-web-wallet#2]
Although there are quite a few references left that refer to cGLD, the name of the token was changed to CELO several months ago. To prevent any misunderstandings, it could be listed as CELO, with a tooltip or other prompt explaining that it used to be cGLD, and either ticker refers to the same token.

**Comment by paychant** [comment]
Hi @barbaraliau, thanks for pointing this out. We have now updated cGLD to CELO.

Thanks.
