### ISSUE TITLE
Celo prices are not updated . It is shown as '0 USD'

### ISSUE THREAD

**Issue by lopeselio** [paychant/celo-web-wallet#3]
![image](https://user-images.githubusercontent.com/43913734/123762777-c0920100-d8e0-11eb-8659-393c9d0f2ad0.png)

![image](https://user-images.githubusercontent.com/43913734/123762816-c982d280-d8e0-11eb-9ada-7208ed478d20.png)

**Comment by paychant** [comment]
Thanks lopeselio, we've updated it, the price should show now
